//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOTIMEMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alert
    {
        public int Alert_ID { get; set; }
        public Nullable<int> C_User_ID { get; set; }
        public Nullable<int> TimeCard_ID { get; set; }
        public Nullable<int> Calendar_ID { get; set; }
        public Nullable<int> Alert_Type_ID { get; set; }
        public string Alert_Description { get; set; }
        public Nullable<bool> Is_Active { get; set; }
    
        public virtual C_User C_User { get; set; }
        public virtual Alert_Type Alert_Type { get; set; }
        public virtual Calendar Calendar { get; set; }
        public virtual Timecard Timecard { get; set; }
    }
}
