//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOTIMEMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_Log
    {
        public int Audit_ID { get; set; }
        public Nullable<int> C_User_ID { get; set; }
        public Nullable<System.DateTime> Audit_TimeStamp { get; set; }
        public string Actor { get; set; }
        public string Action_Performed { get; set; }
        public string EntityType { get; set; }
        public string CriticalData { get; set; }
    
        public virtual C_User C_User { get; set; }
    }
}
