//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOTIMEMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Resource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_Resource()
        {
            this.Employee_Resource = new HashSet<Employee_Resource>();
            this.Employees = new HashSet<Employee>();
        }
    
        public int Resource_ID { get; set; }
        public Nullable<int> Resource_Type_ID { get; set; }
        public Nullable<int> Admin_ID { get; set; }
        public string Resource_Name { get; set; }
        public string Resource_Description { get; set; }
    
        public virtual System_Administrator System_Administrator { get; set; }
        public virtual Resource_Type Resource_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Resource> Employee_Resource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
