//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOTIMEMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendar_Item
    {
        public int Calendar_Item_ID { get; set; }
        public Nullable<int> TimeCard_ID { get; set; }
        public Nullable<int> Calendar_ID { get; set; }
        public Nullable<int> Task_ID { get; set; }
    
        public virtual Calendar Calendar { get; set; }
        public virtual Task Task { get; set; }
        public virtual Timecard Timecard { get; set; }
    }
}
