//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOTIMEMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim_Capture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Claim_Capture()
        {
            this.SubmittedClaimCaptures = new HashSet<SubmittedClaimCapture>();
        }
    
        public int Claim_ID { get; set; }
        public Nullable<int> Project_Allocation_ID { get; set; }
        public Nullable<int> Claim_Status_ID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public byte[] Upload_Proof { get; set; }
        public string ProofName { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual ClaimCaptureStatu ClaimCaptureStatu { get; set; }
        public virtual Project_Allocation Project_Allocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubmittedClaimCapture> SubmittedClaimCaptures { get; set; }
    }
}
