//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOTIMEMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Employee_Resource = new HashSet<Employee_Resource>();
            this.Leaves = new HashSet<Leave>();
            this.Project_Allocation = new HashSet<Project_Allocation>();
            this.Project_Request = new HashSet<Project_Request>();
            this.Tasks = new HashSet<Task>();
            this.Timecards = new HashSet<Timecard>();
            this.Timesheets = new HashSet<Timesheet>();
        }
    
        public int Employee_ID { get; set; }
        public Nullable<int> Resource_ID { get; set; }
        public Nullable<int> Employee_Type_ID { get; set; }
        public Nullable<int> Manager_Type_ID { get; set; }
        public Nullable<int> C_User_ID { get; set; }
        public Nullable<int> Employee_Status_ID { get; set; }
        public Nullable<int> Region_ID { get; set; }
        public Nullable<int> Division_ID { get; set; }
    
        public virtual C_Resource C_Resource { get; set; }
        public virtual C_User C_User { get; set; }
        public virtual Branch_Region Branch_Region { get; set; }
        public virtual Division Division { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Resource> Employee_Resource { get; set; }
        public virtual Employee_Type Employee_Type { get; set; }
        public virtual Employee_Status Employee_Status { get; set; }
        public virtual Manager_Type Manager_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leave> Leaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_Allocation> Project_Allocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_Request> Project_Request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Timecard> Timecards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Timesheet> Timesheets { get; set; }
    }
}
