//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOTIMEMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int History_ID { get; set; }
        public Nullable<int> Timesheet_ID { get; set; }
        public Nullable<System.DateTime> History_Date { get; set; }
        public Nullable<System.TimeSpan> History_Time { get; set; }
        public byte[] Submitted { get; set; }
        public string History_Action { get; set; }
    
        public virtual Timesheet Timesheet { get; set; }
    }
}
