//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOTIMEMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MoTime_DatabaseEntities : DbContext
    {
        public MoTime_DatabaseEntities()
            : base("name=MoTime_DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_Password> C_Password { get; set; }
        public virtual DbSet<C_Resource> C_Resource { get; set; }
        public virtual DbSet<C_User> C_User { get; set; }
        public virtual DbSet<Alert> Alerts { get; set; }
        public virtual DbSet<Alert_Type> Alert_Type { get; set; }
        public virtual DbSet<Audit_Log> Audit_Log { get; set; }
        public virtual DbSet<Branch_Region> Branch_Region { get; set; }
        public virtual DbSet<Calendar> Calendars { get; set; }
        public virtual DbSet<Calendar_Item> Calendar_Item { get; set; }
        public virtual DbSet<Claim_Capture> Claim_Capture { get; set; }
        public virtual DbSet<Claim_Item> Claim_Item { get; set; }
        public virtual DbSet<Claim_Type> Claim_Type { get; set; }
        public virtual DbSet<ClaimCaptureStatu> ClaimCaptureStatus { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Division> Divisions { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Employee_Resource> Employee_Resource { get; set; }
        public virtual DbSet<Employee_Status> Employee_Status { get; set; }
        public virtual DbSet<Employee_Type> Employee_Type { get; set; }
        public virtual DbSet<@event> events { get; set; }
        public virtual DbSet<Help> Helps { get; set; }
        public virtual DbSet<Help_Type> Help_Type { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<IT_Department> IT_Department { get; set; }
        public virtual DbSet<Leave> Leaves { get; set; }
        public virtual DbSet<Leave_Type> Leave_Type { get; set; }
        public virtual DbSet<Manager_Type> Manager_Type { get; set; }
        public virtual DbSet<Maximum_Hours> Maximum_Hours { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Project_Allocation> Project_Allocation { get; set; }
        public virtual DbSet<Project_Request> Project_Request { get; set; }
        public virtual DbSet<Project_Request_Status> Project_Request_Status { get; set; }
        public virtual DbSet<Project_Status> Project_Status { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Resource_Level> Resource_Level { get; set; }
        public virtual DbSet<Resource_Type> Resource_Type { get; set; }
        public virtual DbSet<SubmittedClaimCapture> SubmittedClaimCaptures { get; set; }
        public virtual DbSet<SubmittedProjectRequest> SubmittedProjectRequests { get; set; }
        public virtual DbSet<System_Administrator> System_Administrator { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<Task_Priority> Task_Priority { get; set; }
        public virtual DbSet<Task_Status> Task_Status { get; set; }
        public virtual DbSet<Task_Type> Task_Type { get; set; }
        public virtual DbSet<Timecard> Timecards { get; set; }
        public virtual DbSet<Timesheet> Timesheets { get; set; }
        public virtual DbSet<Timesheet_Status> Timesheet_Status { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<User_Role> User_Role { get; set; }
        public virtual DbSet<User_User_Role> User_User_Role { get; set; }
        public virtual DbSet<UserRolePermission> UserRolePermissions { get; set; }
        public virtual DbSet<Vat> Vats { get; set; }
    }
}
