//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOTIMEMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project_Request()
        {
            this.SubmittedProjectRequests = new HashSet<SubmittedProjectRequest>();
        }
    
        public int Project_Request_ID { get; set; }
        public Nullable<int> Project_Request_Status_ID { get; set; }
        public Nullable<int> Admin_ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public string Project_Request_Description { get; set; }
        public Nullable<System.DateTime> Project_Request_Date { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual System_Administrator System_Administrator { get; set; }
        public virtual Project_Request_Status Project_Request_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubmittedProjectRequest> SubmittedProjectRequests { get; set; }
    }
}
