//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOTIMEMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Allocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project_Allocation()
        {
            this.Claim_Capture = new HashSet<Claim_Capture>();
        }
    
        public int Project_Allocation_ID { get; set; }
        public Nullable<int> Project_ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public Nullable<int> Claim_Item_ID { get; set; }
        public Nullable<int> Total_Num_Hours { get; set; }
        public Nullable<int> Expected_Num_Hours { get; set; }
        public Nullable<int> Billable_OverTime { get; set; }
        public Nullable<bool> IsComplete { get; set; }
        public Nullable<bool> IsEligibleToClaim { get; set; }
        public Nullable<decimal> ClaimableAmount { get; set; }
        public Nullable<bool> IsOperationalManager { get; set; }
        public Nullable<bool> IsProjectManager { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Claim_Capture> Claim_Capture { get; set; }
        public virtual Claim_Item Claim_Item { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Project Project { get; set; }
    }
}
