//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOTIMEMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubmittedProjectRequest
    {
        public int SubmittedProjectRequest_ID { get; set; }
        public int Project_Request_ID { get; set; }
        public System.DateTime Submission_Date { get; set; }
        public int Status_ID { get; set; }
    
        public virtual Project_Request Project_Request { get; set; }
        public virtual Project_Request_Status Project_Request_Status { get; set; }
    }
}
