//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOTIMEMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.Calendar_Item = new HashSet<Calendar_Item>();
        }
    
        public int Task_ID { get; set; }
        public Nullable<int> Project_ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public Nullable<int> Task_Status_ID { get; set; }
        public Nullable<int> Priority_ID { get; set; }
        public Nullable<int> Task_Type_ID { get; set; }
        public string Task_Name { get; set; }
        public string Task_Description { get; set; }
        public Nullable<System.DateTime> Due_Date { get; set; }
        public Nullable<bool> IsComplete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calendar_Item> Calendar_Item { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Project Project { get; set; }
        public virtual Task_Priority Task_Priority { get; set; }
        public virtual Task_Status Task_Status { get; set; }
        public virtual Task_Type Task_Type { get; set; }
    }
}
