//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOTIMEMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_User_Role
    {
        public int User_User_Role_ID { get; set; }
        public Nullable<int> User_Role_ID { get; set; }
        public Nullable<int> C_User_ID { get; set; }
    
        public virtual C_User C_User { get; set; }
        public virtual User_Role User_Role { get; set; }
    }
}
