//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOTIMEMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vat
    {
        public int Vat_ID { get; set; }
        public Nullable<decimal> Vat_Percentage { get; set; }
        public Nullable<System.DateTime> C_Date { get; set; }
    }
}
